language: node_js
env:
  - NODE_OPTIONS=--max_old_space_size=4096
node_js:
  - "8"
sudo: false
install:
  - yarn
script:
  - yarn lint
  - yarn build
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build
    on:
      branch: master
